Starting SLURM job on damnii02.inf.ed.ac.uk
Using GPUs: 0
Folder 00 already exists, skipping extraction.
unzip:  cannot find or open 00.zip, 00.zip.zip or 00.zip.ZIP.
rm: cannot remove '00.zip': No such file or directory
Repo card metadata block was not found. Setting CardData to empty.
Beginning train.py
Using 1 GPUs
OSV5M {'full': False, 'DATASET_DIR': '/disk/scratch/s2751435/my_datasets/osv5m', 'TRAIN_DIR': '/disk/scratch/s2751435/my_datasets/osv5m/images/train', 'TRAIN_CSV': '/disk/scratch/s2751435/my_datasets/osv5m/train.csv', 'name': 'data_test', 'hash': None, 'base_path': None, 'token': None, 'repo_id': None, 'storage_options': {}, 'dataset_name': 'data_test', '_writer_batch_size': None, 'config_kwargs': {}, 'config': BuilderConfig(name='default', version=0.0.0, data_dir=None, data_files=None, description=None), 'config_id': 'default', 'info': DatasetInfo(description='', citation='', homepage='', license='', features={'image': Image(mode=None, decode=True, id=None), 'latitude': Value(dtype='float32', id=None), 'longitude': Value(dtype='float32', id=None), 'thumb_original_url': Value(dtype='string', id=None), 'country': Value(dtype='string', id=None), 'sequence': Value(dtype='string', id=None), 'captured_at': Value(dtype='string', id=None), 'lon_bin': Value(dtype='float32', id=None), 'lat_bin': Value(dtype='float32', id=None), 'cell': Value(dtype='string', id=None), 'region': Value(dtype='string', id=None), 'sub-region': Value(dtype='string', id=None), 'city': Value(dtype='string', id=None), 'land_cover': Value(dtype='float32', id=None), 'road_index': Value(dtype='float32', id=None), 'drive_side': Value(dtype='float32', id=None), 'climate': Value(dtype='float32', id=None), 'soil': Value(dtype='float32', id=None), 'dist_sea': Value(dtype='float32', id=None), 'quadtree_10_5000': Value(dtype='int32', id=None), 'quadtree_10_25000': Value(dtype='int32', id=None), 'quadtree_10_1000': Value(dtype='int32', id=None), 'quadtree_10_50000': Value(dtype='int32', id=None), 'quadtree_10_12500': Value(dtype='int32', id=None), 'quadtree_10_500': Value(dtype='int32', id=None), 'quadtree_10_2500': Value(dtype='int32', id=None), 'unique_region': Value(dtype='string', id=None), 'unique_sub-region': Value(dtype='string', id=None), 'unique_city': Value(dtype='string', id=None), 'unique_country': Value(dtype='string', id=None), 'creator_username': Value(dtype='string', id=None), 'creator_id': Value(dtype='string', id=None)}, post_processed=None, supervised_keys=None, builder_name='data_test', dataset_name='data_test', config_name='default', version=0.0.0, splits={'train': SplitInfo(name='train', num_bytes=32063607, num_examples=50000, shard_lengths=None, dataset_name='data_test')}, download_checksums={}, download_size=0, post_processing_size=None, dataset_size=32063607, size_in_bytes=32063607), '_cache_dir_root': '/home/s2751435/.cache/huggingface/datasets', '_cache_downloaded_dir': '/home/s2751435/.cache/huggingface/datasets/downloads', '_legacy_relative_data_dir': None, '_cache_dir': '/home/s2751435/.cache/huggingface/datasets/data_test/default/0.0.0', '_output_dir': '/home/s2751435/.cache/huggingface/datasets/data_test/default/0.0.0', '_fs': <fsspec.implementations.local.LocalFileSystem object at 0x7ff0af66d700>, 'dl_manager': None, '_record_infos': False, '_file_format': None}
Loaded train dataset! Total of 5 images
after dataset
Number of unique geocells: 11399
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    criterion = HaversineSmoothedLoss()
  File "/home/s2751435/Work/geogettr/loss.py", line 38, in __init__
    quadtree_ids_tensor = quadtree_cluster_ids
NameError: name 'quadtree_cluster_ids' is not defined
SLURM job finished.
